#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

APP_BASE_NAME=`basename "$0"`
APP_HOME=`cd "${APP_BASE_NAME%/*}" >/dev/null 2>&1; pwd -P`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" ] ; then
    case $MAX_FD in
      max*)
        # In POSIX sh, ulimit -H is not portable, so just use the value from ulimit -a
        MAX_FD=`ulimit -a | grep 'open files' | awk '{print $5}'`
        ;;
    esac
    # Set the maximum file descriptors
    ulimit -n $MAX_FD
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
args=""
while [ $# -gt 0 ] ; do
  # Need this for special characters to work
  args="$args \"$1\""
  shift
done

# Set the default JVM options
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "${APP_HOME}"`
    CLASSPATH=`cygpath --path --mixed "${CLASSPATH}"`
fi

# Execute Gradle
eval exec "\"\$JAVACMD\" \$DEFAULT_JVM_OPTS \$JAVA_OPTS \$GRADLE_OPTS -Dorg.gradle.appname=\"\$APP_BASE_NAME\" -classpath \"\$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain \$args"
